# Use a base image suitable for your application (e.g., OpenJDK for Java backend)
FROM openjdk

# Copy the JAR file to the container
COPY ./D387_sample_code-0.0.2-SNAPSHOT.jar /usr/src/D387_sample_code-0.0.2-SNAPSHOT.jar

# Set the working directory
WORKDIR /app

# Expose the port your Spring application runs on
EXPOSE 8080

# Command to run the Spring application
ENTRYPOINT ["java","-jar","/app/D387_sample_code-0.0.2-SNAPSHOT.jar"]
